/**
 * Prints the SQL that loads the real build's starting data (src/data/seed: catalog,
 * delivery fees, payment methods, settings, texts) into the live database, so the
 * site reads from Supabase what it shows today.
 *
 *   node scripts/seed-sql.mjs > supabase/seed.sql
 *
 * Nothing from seed/activity.ts (example orders, DÉMO payment details). Bank and
 * Cash Plus details stay empty, so transfer and Cash Plus stay closed; card is
 * stored switched off until the CMI gateway is connected, so the database itself
 * refuses an order nobody could pay. Products, prices and stock are the examples
 * the site shows until the owner enters the real ones from the Admin Panel.
 * Safe to run twice: rows that already exist are left as they are.
 */
import { seedOrigins, seedProducts } from '../src/data/seed/catalog.ts';
import { seedContent, seedPaymentMethods, seedSettings, seedShippingRates } from '../src/data/seed/config.ts';

const text = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replaceAll("'", "''")}'`);
const json = (v) => `${text(JSON.stringify(v))}::jsonb`;
const values = (rows) => rows.map((r) => `  (${r.join(', ')})`).join(',\n');

// the recipients are owner-only (admin_config); the rest is public (site_config)
const { notifications, ...publicSettings } = seedSettings;
const payeeEmpty = [publicSettings.bank.holder, publicSettings.bank.bankName, publicSettings.bank.rib, publicSettings.cashplus.beneficiary]
  .every((v) => v.trim() === '');
if (!payeeEmpty) throw new Error('seed/config.ts holds payment details: the repository is public, enter them from the Admin Panel');

const sql = `-- ════════════════════════════════════════════════════════════════════
-- BOGA CAFÉ: starting data of the live database.
-- GENERATED by scripts/seed-sql.mjs from src/data/seed: do not edit.
-- Products, prices and stock are examples until the owner enters the real
-- ones from the Admin Panel. No payment details: transfer and Cash Plus stay
-- closed; card stays off until the CMI gateway is connected.
-- Safe to run twice: existing rows are left untouched.
-- ════════════════════════════════════════════════════════════════════
begin;

-- Origins with their opening stock, logged as a restock so the history adds up.
with added as (
  insert into public.origins (id, name, country_code, species, region, roast_level, tasting_notes,
                              stock_kg, low_stock_kg, price_per_kg, custom_blend_enabled, restock_date, active)
  values
${values(seedOrigins.map((o) => [text(o.id), json(o.name), text(o.countryCode), text(o.species), text(o.region), text(o.roastLevel), json(o.tastingNotes), o.stockKg, o.lowStockKg, o.pricePerKg, o.customBlendEnabled, text(o.restockDate), o.active]))}
  on conflict (id) do nothing
  returning id, stock_kg
)
insert into public.stock_movements (origin_id, delta_kg, reason, note)
select id, stock_kg, 'restock', 'Stock initial (exemple)' from added where stock_kg > 0;

insert into public.products (id, slug, kind, name, tagline, description, roast_level, tasting_notes,
                             prices, image_url, featured, active, sort_order)
values
${values(seedProducts.map((p) => [text(p.id), text(p.slug), text(p.kind), json(p.name), json(p.tagline), json(p.description), text(p.roastLevel), json(p.tastingNotes), json(p.prices), text(p.image), p.featured, p.active, p.sortOrder]))}
on conflict (id) do nothing;

-- recipes of the products added above only (a product edited since keeps its own)
insert into public.product_recipes (product_id, origin_id, percent)
select v.product_id, v.origin_id, v.percent
from (values
${values(seedProducts.flatMap((p) => p.recipe.map((r) => [text(p.id), text(r.originId), r.percent])))}
) as v (product_id, origin_id, percent)
where not exists (select 1 from public.product_recipes r where r.product_id = v.product_id);

insert into public.shipping_rates (id, city, distance_km, base_fee, included_kg, extra_per_kg, delivery_days, active)
values
${values(seedShippingRates.map((r) => [text(r.id), json(r.city), r.distanceKm, r.baseFee, r.includedKg, r.extraPerKg, text(r.deliveryDays), r.active]))}
on conflict (id) do nothing;

insert into public.payment_methods (id, enabled, label, instructions)
values
${values(seedPaymentMethods.map((m) => [text(m.id), m.id === 'card' ? false : m.enabled, json(m.label), json(m.instructions)]))}
on conflict (id) do nothing;

insert into public.site_config (id, settings, content)
values (1, ${json(publicSettings)}, ${json(seedContent)})
on conflict (id) do nothing;

insert into public.admin_config (id, admin_whatsapp, admin_email, whatsapp_on, email_on)
values (1, ${text(notifications.adminWhatsapp)}, ${text(notifications.adminEmail)}, ${notifications.whatsappEnabled}, ${notifications.emailEnabled})
on conflict (id) do nothing;

commit;
`;

process.stdout.write(sql);
